export { default as LoginPage } from "./LoginPage";
export { default as NotesPage } from "./NotesPage";
export { default as ColorPickerPage } from "./ColorPickerPage";
export { default as PomodoroPage } from "./PomodoroPage";
export { default as HomePage } from "./HomePage";
export { default as TodoPage } from "./TodoPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as PageNotFound } from "./Error-404Page";
export { default as ErrorPage } from "./Error-404Page";
